
from django.conf.urls import patterns, include, url
from django.contrib import admin
from FileSample import views
from django.contrib import messages
# Los siguientes ficheros son para manejar los ficheros subidos al server.!!! 
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from wkhtmltopdf.views import PDFTemplateView
from FileSample.forms import MyAuthenticationForm, ExampleForm
from django.conf.urls import handler404

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'movie_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # url(r'^admin/', include(admin.site.urls)),
    # url(r'^admin/', include(admin.site.urls)),(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    #url(r'^/userfiles/avatars/', include('avatar.urls')),
    url(r'^newsworker/', views.NoticiaToWorkerListView.as_view(), name='newsworker_index'),
	url(r'^avatar/', include('avatar.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^Inicio$', views.InicioView.as_view(), name='inicio'),
    url(r'^Contactos$', views.ContactosView.as_view(), name='contactos'),
    url(r'^Investigadores$', views.InvestigadoresView.as_view(), name='investigadores'),
	url(r'^Calendario$', views.CalendarView.as_view(), name='calendar'),
	# url(r'^List$', views.FileListView.as_view(), name='file_index'),
	url(r'^Publicaciones$', views.PublicationsListView.as_view(), name='publications_index'),
	url(r'^PublicationEdit/(?P<pk>\d+)$', views.PublicacionUpdateView.as_view(), name='publication_edit'),
	url(r'^Eventos$', views.EventsListView.as_view(), name='events_index'),
	url(r'^EventEdit/(?P<pk>\d+)$', views.EventoUpdateView.as_view(), name='event_edit'),
	url(r'^PonenciasEvento$', views.PonenciaEventoListView.as_view(), name='ponencia_eventos_index'),
	url(r'^PonenciaEventoEdit/(?P<pk>\d+)$', views.PonenciaEventoUpdateView.as_view(), name='ponencia_edit'),
	url(r'^Capacitaciones$', views.CapacitacionListView.as_view(), name='capacitacion_index'),
	url(r'^CapacitacionEdit/(?P<pk>\d+)$', views.CapacitacionUpdateView.as_view(), name='capacitacion_edit'),
	url(r'^Patentes$', views.PatenteListView.as_view(), name='patente_index'),
	url(r'^PatenteEdit/(?P<pk>\d+)$', views.PatenteUpdateView.as_view(), name='patente_edit'),
	url(r'^ProyectosIDi$', views.ProyectoIDiListView.as_view(), name='proyectoidi_index'),
	url(r'^ProyectoIDiView/(?P<pk>\d+)$', views.ProyectoIDiDetailView.as_view(), name='proyectoIDi_view'),
	url(r'^EmpleoEstudiantes$', views.EmpleoEstudiantesListView.as_view(), name='empleoestudiantes_index'),
	url(r'^EmpleoEstudiantesEdit/(?P<pk>\d+)$', views.EmpleoEstudiantesUpdateView.as_view(), name='empleoestudiantes_edit'),
	url(r'^ProyectoIDiEdit/(?P<pk>\d+)$', views.ProyectoIDiUpdateView.as_view(), name='proyectoidi_edit'),
	url(r'^ResultadosIntroducidos$', views.ResultadoIntroducidoListView.as_view(), name='resultadointroducido_index'),
	url(r'^ResultadoIntroducidoEdit/(?P<pk>\d+)$', views.ResultadoIntroducidoUpdateView.as_view(), name='resultadointroducido_edit'),
	url(r'^Premios$', views.PremioListView.as_view(), name='premio_index'),
	url(r'^PremioEdit/(?P<pk>\d+)$', views.PremioUpdateView.as_view(), name='premio_edit'),
	url(r'^Noticias$', views.NoticiaListView.as_view(), name='noticia_index'),
	url(r'^NoticiaEdit/(?P<pk>\d+)$', views.NoticiaUpdateView.as_view(), name='noticia_edit'),
	url(r'^ObraCientificaEdit/(?P<pk>\d+)$', views.ObraCientificaUpdateView.as_view(), name='obra_edit'),
	url(r'^SAIEdit/(?P<pk>\d+)$', views.SAIUpdateView.as_view(), name='sai_edit'),
	url(r'^SAIEditAprobacion/(?P<pk>\d+)$', views.SAIUpdateAprobacionView.as_view(), name='sai_editAprobacion'),
	url(r'^SAIEditEvaluacion/(?P<pk>\d+)$', views.SAIUpdateEvaluacionView.as_view(), name='sai_editEvaluacion'),
	url(r'^PublicacionView/(?P<pk>\d+)$', views.PublicacionDetailView.as_view(), name='publicacion_view'),
	url(r'^EventoView/(?P<pk>\d+)$', views.EventoDetailView.as_view(), name='evento_view'),
	url(r'^PonEnvView/(?P<pk>\d+)$', views.PonenciaEventoDetailView.as_view(), name='ponenciaevento_view'),
	url(r'^CapacitacionView/(?P<pk>\d+)$', views.CapacitacionDetailView.as_view(), name='capacitacion_view'),
	url(r'^PatenteView/(?P<pk>\d+)$', views.PatenteDetailView.as_view(), name='patente_view'),
	url(r'^ResultadoIntroducidoView/(?P<pk>\d+)$', views.ResultadoIntroducidoDetailView.as_view(), name='ri_view'),
	url(r'^PremioView/(?P<pk>\d+)$', views.PremioDetailView.as_view(), name='premio_view'),
	url(r'^NoticiaView/(?P<pk>\d+)$', views.NoticiaDetailView.as_view(), name='noticia_view'),
	url(r'^NoticiaTrabajadorView/(?P<pk>\d+)$', views.NoticiaTrabajadorDetailView.as_view(), name='noticiaworker_view'),
	url(r'^EmpleoView/(?P<pk>\d+)$', views.EmpleoEstudiantesDetailView.as_view(), name='empleo_view'),
	url(r'^ObraCientificaView/(?P<pk>\d+)$', views.ObraCientificaDetailView.as_view(), name='obra_view'),
	url(r'^InvestigadorView/(?P<pk>\d+)$', views.InvestigadorDetailView.as_view(), name='investigador_view'),
	url(r'^ModelsList$', views.ModelsListView.as_view(), name='models_index'),
	url(r'^ObrasCientificas$', views.ObraCientificaListView.as_view(), name='obras_index'),
	url(r'^SAIs$', views.SAIListView.as_view(), name='sais_index'),
	url(r'^Usuarios$', views.UsersListView.as_view(), name='users_index'),
	url(r'^SAIView/(?P<pk>\d+)$', views.SAIDetailView.as_view(), name='sai_view'),
	url(r'^$', views.InicioView.as_view(), name='file_index'),
	# url(r'^create$', views.FileCreate.as_view(), name='file_create'),
	# url(r'^createMixin$', views.CreateViewMixin.as_view(), name='movies_createMixin'),
	# url(r'^edit/(?P<pk>\d+)$', views.UpdateView.as_view(), name='movies_edit'),
	url(r'^delete/(?P<pk>\d+)$', views.DeleteView.as_view(), name='file_delete'),
	url(r'^deletePub/(?P<pk>\d+)$', views.PublicacionDeleteView.as_view(), name='publication_delete'),
	url(r'^deleteEvn/(?P<pk>\d+)$', views.EventoDeleteView.as_view(), name='event_delete'),
	url(r'^deletePonEvn/(?P<pk>\d+)$', views.PonenciaEventoDeleteView.as_view(), name='ponencia_delete'),
	url(r'^deleteCap/(?P<pk>\d+)$', views.CapacitacionDeleteView.as_view(), name='capacitacion_delete'),
	url(r'^deletePa/(?P<pk>\d+)$', views.PatenteDeleteView.as_view(), name='patente_delete'),
	url(r'^deleteRI/(?P<pk>\d+)$', views.ResultadoIntroducidoDeleteView.as_view(), name='resultadointroducido_delete'),
	url(r'^deleteEE/(?P<pk>\d+)$', views.EmpleoEstudiantesDeleteView.as_view(), name='empleoestudiantes_delete'),
	url(r'^deleteRre/(?P<pk>\d+)$', views.PremioDeleteView.as_view(), name='premio_delete'),
	url(r'^deleteNew/(?P<pk>\d+)$', views.NoticiaDeleteView.as_view(), name='noticia_delete'),
	url(r'^deleteObraCientifica/(?P<pk>\d+)$', views.ObraCientificaDeleteView.as_view(), name='obra_delete'),
	url(r'^deleteProyectoIDi/(?P<pk>\d+)$', views.ProyectoIDiDeleteView.as_view(), name='proyecto_delete'),
	url(r'^deleteSAI/(?P<pk>\d+)$', views.SAIDeleteView.as_view(), name='sai_delete'),
	url(r'^deleteUser/(?P<pk>\d+)$', views.UserDeleteView.as_view(), name='user_delete'),
	url(r'^createPub$', views.PublicacionCreate.as_view(), name='pub_create'),
	url(r'^createEvn$', views.EventoCreate.as_view(), name='evn_create'),
	url(r'^createPonEvn$', views.PonenciaEventoCreate.as_view(), name='ponevn_create'),
	url(r'^createProjIDi$', views.ProyectoIDiCreate.as_view(), name='projIDi_create'),
	url(r'^createCap$', views.CapacitacionCreate.as_view(), name='cap_create'),
	url(r'^createPa$', views.PatenteCreate.as_view(), name='pa_create'),
	url(r'^createRI$', views.ResultadoIntroducidoCreate.as_view(), name='ri_create'),
	url(r'^createPre$', views.PremioCreate.as_view(), name='pre_create'),
	url(r'^createPremioPublicacion$', views.PremioPublicacionCreate.as_view(), name='prepu_create'),
	url(r'^createPremioPonencia$', views.PremioPonenciaCreate.as_view(), name='prepo_create'),
	url(r'^createPremioProyecto$', views.PremioProyectoCreate.as_view(), name='prepro_create'),
	url(r'^createPremioObra$', views.PremioObraCreate.as_view(), name='preobra_create'),
	url(r'^createEp$', views.EmpleoEstudiantesCreate.as_view(), name='Ep_create'),
	url(r'^createEmpleoPublicacion$', views.EmpleoEstudiantesPublicacionCreate.as_view(), name='EpPu_create'),
	url(r'^createEmpleoPonencia$', views.EmpleoEstudiantesPonenciaCreate.as_view(), name='EpPo_create'),
	url(r'^createEmpleoProyecto$', views.EmpleoEstudiantesProyectoCreate.as_view(), name='EpPro_create'),
	url(r'^createEmpleoObra$', views.EmpleoEstudiantesObraCreate.as_view(), name='EpOb_create'),
	url(r'^createNew$', views.NoticiaCreate.as_view(), name='New_create'),
	url(r'^createObra$', views.ObraCientificaCreate.as_view(), name='Obra_create'),
	url(r'^createSAI$', views.SAICreate.as_view(), name='SAI_create'),
	url(r'^createModeloYoamel$', views.ModeloYoamelCreate.as_view(), name='ModeloYoamel_create'),
	# url(r'^ciudades/$', 'FileSample.ajax.get_sectors', name='get_ciudades'),
	url(r'^ciudades/$', 'FileSample.ajax.delete_post', name='get_ciudades'),
	url(r'^PublicationEdit/ciudades/$', 'FileSample.ajax.delete_post', name='get_ciudades'),
	url(r'^EventEdit/ciudades/$', 'FileSample.ajax.delete_post', name='get_ciudades'),
	url(r'^PonenciaEventoEdit/ciudades/$', 'FileSample.ajax.delete_post', name='get_ciudades'),
	url(r'^CapacitacionEdit/ciudades/$', 'FileSample.ajax.delete_post', name='get_ciudades'),
	url(r'^PatenteEdit/ciudades/$', 'FileSample.ajax.delete_post', name='get_ciudades'),
	url(r'^PremioEdit/ciudades/$', 'FileSample.ajax.delete_post', name='get_ciudades'),
	url(r'^admin/jsi18n/$', 'django.views.i18n.javascript_catalog'),
	url(r'^Relacionado/$', 'FileSample.ajax.test', name='relacionado'),
	url(r'^search/', views.search, name='get_drugs'),
	url(r'^samplePDF/', views.samplePDF, name='get_pdfSample'),
	url(r'^capacitacionesCSV/', views.capacitacionesCSV, name='get_csvCapacitaciones'),
	url(r'^publicacionesCSV/', views.publicacionesCSV, name='get_csvPublicaciones'),
	url(r'^eventosCSV/', views.eventosCSV, name='get_csvEventos'),
	url(r'^ponenciasCSV/', views.ponenciasCSV, name='get_csvPonencias'),
	url(r'^patentesCSV/', views.patentesCSV, name='get_csvPatentes'),
	url(r'^resultadosCSV/', views.resultadosCSV, name='get_csvResultados'),
	url(r'^premiosCSV/', views.premiosCSV, name='get_csvPremios'),
	url(r'^noticiasCSV/', views.noticiasCSV, name='get_csvNoticias'),
	url(r'^EmpleoEstudiantesCSV/', views.empleoEstudiantesCSV, name='get_csvEmpleoEstudiantes'),
	url(r'^ObrasCientificasCSV/', views.ObraCientificaCSV, name='get_csvObrasCientificas'),
	url(r'^ProyectosIDiCSV/', views.ProyectoIDiCSV, name='get_csvProyectosIDi'),
	url(r'^SAICSV/', views.SAICSV, name='get_csvSAI'),
	url(r'^UsuariosCSV/', views.UsuariosCSV, name='get_csvUser'),
	url(r'^Ranking$', views.Ranking, name='ranking'),
	url(r'^Resultados$', views.Resultados, name='resultados'),
	url(r'^InformeCienciaTecnica$', views.InformeCienciaTecnica, name='informe_ciencia_tecnica'),
	url(r'^searchPub/$', 'FileSample.ajax.searchPublicacion', name='searchPub'),
	url(r'^searchEvn/$', 'FileSample.ajax.searchEvento', name='searchEvn'),
	url(r'^searchPonEvn/$', 'FileSample.ajax.searchPonenciaEvento', name='searchPonEvn'),
	url(r'^searchCap/$', 'FileSample.ajax.searchCapacitacion', name='searchCap'),
	url(r'^searchPat/$', 'FileSample.ajax.searchPatente', name='searchPat'),
	url(r'^searchRI/$', 'FileSample.ajax.searchResultadoIntroducido', name='searchRI'),
	url(r'^searchPre/$', 'FileSample.ajax.searchPremio', name='searchPre'),
	url(r'^searchNew/$', 'FileSample.ajax.searchNoticia', name='searchNew'),
	url(r'^searchInv/$', 'FileSample.ajax.getInvestigadores', name='searchInv'),
	url(r'^searchObrasCientificas/$', 'FileSample.ajax.getObrasCientificas', name='searchObrasCientificas'),
	url(r'^searchPublicaciones/$', 'FileSample.ajax.getPublicaciones', name='searchPublicaciones'),
	url(r'^searchPonencias/$', 'FileSample.ajax.getPonencias', name='searchPonencias'),
	url(r'^searchProyectos/$', 'FileSample.ajax.getProyectos', name='searchProyectos'),
	url(r'^samplePrint/$', views.samplePrint, name='searchNew'),
	url(r'^PublicacionesPdf/$', views.MyPDFViewPublicaciones, name='pdfpublicaciones'),
	url(r'^EventosPdf/$', views.MyPDFViewEventos.as_view(), name='pdfeventos'),
	url(r'^PonenciasPdf/$', views.MyPDFViewPonencias, name='pdfponencias'),
	url(r'^CapacitacionesPdf/$', views.MyPDFViewCapacitaciones, name='pdfcapacitaciones'),
	url(r'^PatentesPdf/$', views.MyPDFViewPatentes, name='pdfpatentes'),
	url(r'^ResultadosIntroducidosPdf/$', views.MyPDFViewResultadosIntroducidos, name='pdfresultadosintroducidos'),
	url(r'^EmpleoEstudiantesPdf/$', views.MyPDFViewEmpleoEstudiantes, name='pdfrempleoestudiantes'),
	url(r'^PremiosPdf/$', views.MyPDFViewPremios, name='pdfpremios'),
	url(r'^NoticiasPdf/$', views.MyPDFViewNoticias, name='pdfnoticias'),
	url(r'^ObrasCientificasPdf/$', views.MyPDFViewObrasCientificas, name='pdfobrascientificas'),
	url(r'^ProyectosIDiPdf/$', views.MyPDFViewProyectosIDi, name='pdfproyectosIDi'),
	url(r'^SAIPdf/$', views.MyPDFViewSAI, name='pdfSAI'),
	url(r'^UsuariosPdf/$', views.MyPDFViewUsers, name='pdfUsuarios'),
	url(r'^summernote/', include('django_summernote.urls')),
	url(r'^login/$', 'django.contrib.auth.views.login', {'template_name':'registration/login.html', 'authentication_form':MyAuthenticationForm, 'redirect_field_name':'/Files/'}, name='loguin'),
	url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': 'inicio'}, name='logout'),
	url(r'^password_change/$', 'django.contrib.auth.views.password_change', name='password_change',kwargs={
               'template_name': 'registration/password_change_form.html','password_change_form':ExampleForm,
               'post_change_redirect':'password_change_done',
               }),
    url(r'^password_change_done/$','django.contrib.auth.views.password_change_done',name='password_change_done',
        kwargs={'template_name': 'registration/password_change_done.html'}
    ),
    # url(r'^settings/$', views.UserEdit.as_view(), name='settings'),
    # url(r'^settings/$', views.editar_perfil, name='settings'),
    url(r'^cambiarPerfil/$', views.TeacherUpdate.as_view(), name='settings'),
    # url(r'^nuevoUsuario/$', views.TeacherCreation.as_view(), name='newUser'),
    # url(r'^nuevoUsuario1/$', views.AlainCreate.as_view(), name='newUser1'),
    url(r'^nuevoUsuario/$', views.register, name='register'), # ADD NEW PATTERN!
	url(r'^editarUsuario/(?P<pk>\d+)$', views.UsuarioUpdate.as_view(), name='user_edit'),
	url(r'^vamos/$', views.submit_recipe, name='vamos'), # ADD NEW PATTERN!
    #url(r'^alain/$', views.CreateOrderView.as_view(), name='alain'),
    #handler404,
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#handler404 = views.handler404


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'userfiles/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )   
# Solucionado el tema de la carga de fichero css para las páginas que no cargaban + el bloque anterior  
urlpatterns += staticfiles_urlpatterns()